server.port=3000

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?
spring.datasource.username=postgres.motilleztkeccyzyrnyz
spring.datasource.password=5lV5lVJvR3tFgAd6

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=YourSuperSecretKeyForJWTTokenGeneration12345678901234567890
jwt.expiration=86400000