server.port=3000

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.motilleztkeccyzyrnyz
spring.datasource.password=5lV5lVJvR3tFgAd6

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=20000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

assetflow.upload-dir=uploads/assets
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB

# JWT Configuration
jwt.secret=YourSuperSecretKeyForJWTTokenGeneration12345678901234567890
jwt.expiration=86400000